### ISSUE TITLE
Add option to ignore uncommitted changes

### ISSUE THREAD

**Issue by ahimberg** [microsoft/beachball#107]
Every time I'm trying to commit in react-native-windows I'm running into extra pain with yarn change files.  I've already committed everything but have other local files and it won't let me create a change file...

For example, I have a local vscode setting so browse files are stored per project instead of on my C: drive, I have to close vscode and delete the files

$ node ./node_modules/beachball/bin/beachball.js change
Target branch is "upstream/master"
ERROR: There are uncommitted changes in your repository. Please commit these files first:
- .vscode/.BROWSE.VC.DB-shm
- .vscode/.BROWSE.VC.DB-wal
error Command failed with exit code 1.

**Comment by kenotron** [comment]
There's a workaround, but I want to fix this as well. The workaround would be to place .DB-* in .gitignore for now.

**Comment by kenotron** [comment]
@ahimberg - I have a change coming that should address this issue for you. In fact, this should have been the default all along, so I'm just allowing it ... but it will give you a warning that you have untracked files: #134

When this is merged and published, you can upgrade `beachball` to get rid of any workarounds.

**Comment by kenotron** [comment]
This has been published as `beachball@1.13.0`! 

ATTN: @leeviana and @christiango
