### ISSUE TITLE
Add the ability to ignore certain files

### ISSUE THREAD

**Issue by kenotron** [microsoft/beachball#135]
Should we have a .beachballignore file or maybe an entry in the package.json like we already have?

**Comment by kenotron** [comment]
I think we should target reusing the beachball key in the package.json. This way we avoid adding more config files around for now. We can think more holistically about config in another change.

**Comment by lynamemi** [comment]
Hey @kenotron ! Was thinking about this one recently. Is this something I can help with? What does this entail:
> target reusing the beachball key in the package.json

**Comment by kenotron** [comment]
I made beachball check to no longer barf on uncommitted files... does that address your needs?

**Comment by lynamemi** [comment]
The original need was to make it so PRs with just Markdown files edited could be merged in without change files (and associated build errors) so I don't think so.

**Comment by kenotron** [comment]
So the part you're looking for is something inside getChangedPackages.

**Comment by lynamemi** [comment]
Ok cool, I'll take a look.

**Comment by lynamemi** [comment]
Looks like something like this might work? Although given this is an open source library and not in OUIFR, probably a bad idea to bake this in, which probably brings us back to a `.beachballignore` file. Thoughts?
```typescript
function getAllChangedPackages(branch: string, cwd: string) {
  ...
  const ignoredFiles = ['CHANGELOG.md', 'CHANGELOG.json', '*.md'];
  ...
}
```

**Comment by dpouliot** [comment]
On the one year anniversary since the last comment, I'd like to add my vote for this feature! We have .stories.jsx and docs.mdx files that are triggering changes; it would be great if we could skip documentation.

**Comment by ecraig12345** [comment]
Added awhile back in #593
