### ISSUE TITLE
Beachball change file "file" attribute contains full path

### ISSUE THREAD

**Issue by KevinTCoughlin** [microsoft/beachball#183]
The value for "file" in the Beachball change file schema currently contains the full path on disk e.g. https://github.com/OfficeDev/office-ui-fabric-react/pull/10941/files#diff-795147d4185c2ea960552d4a0378b629R8

This exposes internals of the Users machine and is a privacy concern. Ideally, beachball only emits the relative file path.

Note that this can also lead to undesirable language being generated by Beachball and subsequently committed to a repository.

I'm willing to fix assuming the full path is not intentional i.e. part of Beachball's design.

**Comment by kenotron** [comment]
This is a dupe of #175 - the fix is out but needs consumers to update their deps.
