### ISSUE TITLE
Packages whose dependencies change should be published

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/beachball#189]
Currently If I have 2 packages:

Package A: 
```
{
  dependencies: {
    packageB: "1.0.3"
  }
}
```

And I publish package B, it correctly updates the dependencies of package A, but it doesn't publish package A with the new dependencies.  This means users of package A will never see the new version of package B.

We should have some kind of option to configure `beachball` to be more aggressive about publishing updates when their dependencies change.

**Comment by kenotron** [comment]
Do you have a suggestion for the name of this option? "publish all affected"
