### ISSUE TITLE
If "beachball publish" is run, and the only change file changeTypes are "none", they are not removed and pushed back to the repo

### ISSUE THREAD

**Issue by josephliccini** [microsoft/beachball#190]
If, in my `/change` directory, I have a set of Change Files like this:
```json
{
  "type": "none",
  "comment": "A Noop Change",
  "packageName": "@scope/some-package",
  "email": "someone@something.com",
  "commit": "hash",
  "date": "2019-10-30T22:32:50.474Z"
}

{
  "type": "none",
  "comment": "A Noop Change",
  "packageName": "@scope/some-package2",
  "email": "someone@something.com",
  "commit": "hash",
  "date": "2019-10-30T22:32:50.474Z"
}

{
  "type": "none",
  "comment": "A Noop Change",
  "packageName": "@scope/another-package",
  "email": "someone@something.com",
  "commit": "hash",
  "date": "2019-10-30T22:32:50.474Z"
}
```

Notice that they are all of `type` `none`.

When the CI runs `beachball publish`, the files will be deleted (can be simulated with `beachball bump` locally) but since there is nothing to publish, beachball does note commit those removed files and push back to the repo.

The result is that the "none" files were continue to live in the repo until a minor, major, or patch change is made, and then they will be commit back to the repo.

I'd expect these to be commit back, placed in the `CHANGELOG.json`, even if they are marked as `none` changes.

**Comment by kenotron** [comment]
I believe this fixes this issue: #192
