### ISSUE TITLE
Add message that change file has been committed

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/beachball#2]
Right now there's not an obvious indication that beachball has just committed the changefile it created. It would be helpful to add a message, something like this (showing the full output as an example):
```
Please describe the changes for: office-ui-fabric-react
✔ Describe changes (type or choose one) › SearchBox: allow passing in id for input
✔ Change type › Patch - bug fixes; no backwards incompatible changes.

Created and committed /path/to/change/file!
Be sure to push this commit to your remote branch.
```

<img src="https://media.giphy.com/media/l3Ucp3dHbQIZ8m7ba/giphy.gif" width=300/>

**Comment by acoates-ms** [comment]
Is the beachball gif part of the suggested output?

**Comment by ecraig12345** [comment]
That would be funny, but no. :)

**Comment by kenotron** [comment]
I added this by listing all the files committed - didn't say anything about pushing tho because that might not be what users would need to do immediately next
