### ISSUE TITLE
Allow specific local edits during publish

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/beachball#206]
The azure dev ops npmAuthenticate task edits the local .npmrc file.

In order to use this with beachball publish, beachball needs to be able to run publish with local edits in the repo.  Currently it looks like beachball reverts any local edits before publish.

We may also need the capability of editing files during publish if we want to enable typescript workspaces where we change to a .js entry file during publish, but have .ts internal to the repo?  (I could be wrong about that).

It could also allow apps to run custom prepare publish scripts as part of their CI pipelines, to possibly set version numbers in source code before publishing.

Note, with the npmAuthenticate issue at least, we'd want to make sure that beachball publish doesn't actually commit that change to the repo when commit its other changes.

**Comment by kenotron** [comment]
Is this still happening? I think I had addressed this for publish (we needed to fix this to address the set-version thing in Fabric)

**Comment by ecraig12345** [comment]
I think this should be fixed now with the addition of `hooks.prepublish` in the beachball config file (you just have to use a JS config file since the hook is a function).

**Comment by ecraig12345** [comment]
Not in the official docs yet but here it is in the repo.
https://github.com/microsoft/beachball/blob/7af5c93ec181dd9e9cd90e2a072c7cc6677ae2a2/src/types/BeachballOptions.ts#L67-L82
