### ISSUE TITLE
Updating from Beachball 1.18.1 to 1.18.2 Causes Hangs During Version Bump

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/beachball#241]
See https://github.com/microsoft/react-native-windows/issues/3896

Steps to repro:

1. Clone react-native-windows repo at commit 7d6357f5aeb5f15d3708d306af7600fb1e7426cd
2. cd into new directory
2. Run "yarn install"
3. Run "npx beachball publish --no-push --no-publish"

Reverting commit 1c8cbe8e79ff30ffb712a36e52ad28d6b891f031, which updated our lockfile resolves the hang.

**Comment by kenotron** [comment]
Thx for the heads up. Will look into it today.

**Comment by kenotron** [comment]
This should be fixed now! Please update and then try to republish (I tested the --no-push --no-publish locally the react-native-windows with the latest beachball fixes, seems okay).
