### ISSUE TITLE
ChangeLog: Support customized CHANGELOG.md generation 

### ISSUE THREAD

**Issue by xugao** [microsoft/beachball#276]
Provide a way for beachball user to define freely how to render CHANGELOG.md 
Currently beachball renders as:
https://github.com/microsoft/beachball/blob/01f3bae061bdd91a1e2971fd81a82dc22779bf9e/packages/beachball/src/changelog/renderChangelog.ts#L3

**Comment by ecraig12345** [comment]
I think we fixed this one.
