### ISSUE TITLE
Feature: Handle partial publishes

### ISSUE THREAD

**Issue by kenotron** [microsoft/beachball#29]
Handle partial publishes:

minispec:

- add a "sync" command that can synchronize a partially updated git repo with the current versions of the published npm packages. 
- ~delete change files for a subset of these~
- ~should mark partially upgraded versions to be unpublished and set latest dist-tag to the last known good~
- ~on publish AGAIN, make sure to skip over unpublished versions and apply a patch (with a changelog entry) about the skipped version~

**Comment by kenotron** [comment]
@leeviana @christiango - please do chime in to see if you can give more detail to the spec.

**Comment by leeviana** [comment]
Discussed a similar problem today and came up with another potential solution: retry fetch/push step (since this is what often fails) when there are issues.

**Comment by kenotron** [comment]
@dzearing - this came up again when npm had an outage during our publish time.

**Comment by kenotron** [comment]
The mini spec is too magical. We cannot guarantee these actions will address the issues. What we should do is only do the first line (sync command)
