### ISSUE TITLE
Automatically recover if package version already exists in the registry

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/beachball#292]
If the requested package version already exists in the registry, it would be nice if beachball could increment the version and try again instead of bailing out. (Might still have to bail out if the version which already exists is a prerelease, since those are harder to increment automatically.)

**Comment by kenotron** [comment]
I added a retry - but what do you incremental version to? a new patch or a new minor, or... ?

**Comment by ecraig12345** [comment]
Probably new patch. Though if the current version is a prerelease it might just have to bail since there's not a clear way to increment that.

**Comment by ecraig12345** [comment]
Though I guess if it incremented to a new patch, if the next minor version also exists already somehow, that could be a problem... (though that seems a bit less likely to come up)

I've been thinking about the recovery problem all-up and it generally seems like any recovery options would have to either be interactive, or (for running in CI) have very specific options for which recovery strategy to try, very specific verification of expectations, and bail out if those expectations aren't met.

**Comment by ecraig12345** [comment]
Despite the challenges, I do think it's worth implementing some kind of recovery mode(s) that can be run in CI, so that on a large team, multiple people could do it if needed without special credential access, special knowledge, or lots of manual steps.

**Comment by ecraig12345** [comment]
A more minimal version of this would be to add a manual option for running something like the script @dzearing added for fluentui, to update the local package versions to be in sync with the current npm version: 
https://github.com/microsoft/fluentui/blob/master/scripts/recover-package-versions.js

If we added this in beachball we'd want extra logic to ensure we're doing `npm view` on the same major version as in the local copy.

**Comment by christiango** [comment]
Automated recovery would be super useful! I think getting the local package versions to be in sync with the current npm version is a good solution,

**Comment by ecraig12345** [comment]
This is actually semi-automated now--there's a new command `beachball sync` which does basically what I mentioned above (the issue just didn't get closed for some reason). I think that's actually a better option than attempting fully automated recovery, since it's safer.
