### ISSUE TITLE
Feature Request: Allow Publishing to NPM Without Tagging

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/beachball#296]
React Native Windows is wanting to move to a model where we have tags for "master", "latest", and "preview". Apart from these tags, we often backport fixes into previous versions. Ideally we could avoid tagging these older releases, but currently publishing forces a tag, defaulting to "latest" if none is specified. To avoid polluting latest with backports, we've been explicitly changing old branches to publish a tag based on their branch name. This ends up leading to a bunch of unnecessary NPM tags causing clutter.

Ideally, we should be able to ask Beachball while publishing not to add a dist-tag to prevent tagging our backport fixes that we still want to publish.

**Comment by kenotron** [comment]
Why don't you have a "master" tag that's the default and then manually tag latest later?

**Comment by kenotron** [comment]
I think you could also just use a "dummy" tag as well (call it "dev" say)

**Comment by NickGerleman** [comment]
We do actually have a "master" tag that's the default and separate from "latest". We have a branch per released version of React Native that sees some amount of parallel development though. Currently the most recent released branch will publish as "latest. We definitely want to automate that part, since different engineers will frequently backport fixes to this branch, and manually tagging wouldn't scale here.

The issue ends up being the other branches which fixes will also get backported to, but don't correspond to the latest version we support, or our master. These releases don't correspond to anything we would want to tag. We could have a common dummy tag for the old branches, but that's not particularly clean. We'd basically see "dev" point to different interleaved branches based on when things get backported, so it ends up not being particularly useful. This is why we currently have a tag per-old branch.

**Comment by ecraig12345** [comment]
At some point this was implemented as the repo or package level option `gitTags: false`.
