### ISSUE TITLE
Validate package dependencies not being private packages

### ISSUE THREAD

**Issue by xugao** [microsoft/beachball#321]
before we publish, we should validate if package contains deps which are private. to prevent mistakes like: https://github.com/microsoft/fluentui/commit/e7d03cc930fa094538adf9d272b312e21ed934b5

**Comment by dzearing** [comment]
I believe this should happen at `change` prompts. When a package is being changed, just validate then. That way the dev has a chance to fix before creating a change file.

**Comment by kenotron** [comment]
you need to validate at the publish level AS WELL actually because change file can be... well... changed :)
