### ISSUE TITLE
Publish dependencies first then dependents

### ISSUE THREAD

**Issue by xugao** [microsoft/beachball#322]
If package A depends on package B, we should publish B first then A.

**Comment by kenotron** [comment]
We need to do a topological sort for publishes, it seems. How about we use this package?

https://www.npmjs.com/package/toposort

**Comment by dzearing** [comment]
this is a pretty big regression. I believe rush publish always did this. This should be fixed asap. It causes major customer friction when things fail which leaves packages in a broken state.

**Comment by kenotron** [comment]
https://github.com/microsoft/rushstack/blob/a420d7497fc19c5ddfb54cf90b2ab8067ee143d6/apps/rush-lib/src/logic/PublishUtilities.ts#L90 

for reference
