### ISSUE TITLE
Beachball check should catch PRs that add private dependencies to publish packages

### ISSUE THREAD

**Issue by christiango** [microsoft/beachball#331]
We've had this scenario happen a few times.

Repo has private package and a public package. Developer updates dependencies of public package to depend on private package. Consumers of public package are now broken because they can't install the private package that appears in public package's package.json.

Proposal is to have beachball change prevent these changes from being merged and to have beachball publish prevent these changes from being published

**Comment by ecraig12345** [comment]
I think @xugao actually just added this a few days ago?

**Comment by xugao** [comment]
I added check before publish in #324. But that doesn't catch the issue before merging. we can consider add check during `beachball check`

**Comment by ecraig12345** [comment]
I just recently fixed this. :) #483

**Comment by christiango** [comment]
Thank you @ecraig12345!
