### ISSUE TITLE
Suggestion: add --nocommit flag for change

### ISSUE THREAD

**Issue by dzearing** [microsoft/beachball#379]
It's often confusing for a customer when the change file gets committed but not merged. It creates more of a half black box experience; what happens after yarn change, and even then, why do i need to push?

Recommend adding a `--nocommit` flag so that we can default to just creating the json file and leaving it in the changelist. This way the user can know what's going on and can manage tweaking it before commit/push.

**Comment by ecraig12345** [comment]
At some point a `--no-commit` flag was added
