### ISSUE TITLE
Allow remote to be specified by url

### ISSUE THREAD

**Issue by dannyvv** [microsoft/beachball#460]
To run `beachball change` the upstream is ideally the main branch of the main repo.
Some engineers clone their github fork whereas others clone the main github repo and push to their fork for PR's.

The fix is to pass `--branch <remote>/<branchname>`.
A common pattern is to add a `yarn change` shortcut in the scripts of package.json. adding that branch setting there causes problems with the remote names.

The current workaround I have created is the following script:
```
{
  ...
  "scripts": {
    ...
    "change": "powershell -NoProfile -Command $remoteLine = \"git remote -v | Select-String -Pattern '(fetch)' | Select-String -pattern 'https://github.com/microsoft/react-native-windows';$remote = ('' + $remoteLine).split()[0];beachball change --branch $remote/master\"",
```

It would be nice if we could have the following either:
`beachball change --branch "[https://github.com/microsoft/react-native-windows]/master"`
or
`beachball change --remote "https://github.com/microsoft/react-native-windows" --branch "master"`

**Comment by asklar** [comment]
To clarify, this is a recent _breaking change_ which is affecting React Native for Windows. This has impacted several engineers' workflows. We used to be able to run `yarn change` (which runs `beachball change`) and it would find the right branch/packages that had changes, but recently something changed (we took a beachball update, likely), and if you run that command now it finds changes (and requires change files) for all the packages in our repo.

**Comment by kenotron** [comment]
I think you could also affect this by using the "repository" setting in the package.json itself... @dannyvv, can you check if that helps you?

**Comment by ecraig12345** [comment]
Sometime last year I added [code](https://github.com/microsoft/workspace-tools/pull/34/files#diff-3b1c3a5a0d0ca1ef08b3d3cdb46c97a9efa983ea28348a3454b3cbddd97eb2fd) that should automatically detect the correct default remote if you set `repository` in the repo root package.json. So setting a repository and passing `--branch` *without* a remote name is the recommended solution here. If that doesn't work, please file a new issue with details.
