### ISSUE TITLE
change command: allow opt out behaviour from automatic commit

### ISSUE THREAD

**Issue by Hotell** [microsoft/beachball#479]
Currently `beachball change` does a lot of magic... which is not always  a good think.

From my experience it's always a good idea to provide opt out behaviour for various reasons.

**Feature request:**
adding `--no-commit` to `change` command so changes are generated to the file system but not committed automatically

**Comment by kubkon** [comment]
@Hotell fixed in #481 so I guess we can close this issue now.

**Comment by Hotell** [comment]
Closed by #481
