### ISSUE TITLE
Dependency bump leads to changelog generation for unbumped private packages

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/beachball#480]
Steps to repro:
- Package A depends on monorepo package B
- Package A is private
- Package B is updated

Package A is not bumped, but changelog entries are added for the bumped dependency, generating a changelog where all versions are the same, only including dependency bumps. 

See "@react-native-windows/tester" in https://github.com/microsoft/react-native-windows/commit/0312f90ccb9a20b5726277107e8aae6b38a4448f

**Comment by ecraig12345** [comment]
I wonder if this has to do with the `--bump-deps` option? `microsoft/fluentui` has a similar setup with a mix of published and private packages, but we don't use that option, and we've never had issues like you described.
https://github.com/microsoft/react-native-windows/blob/0312f90ccb9a20b5726277107e8aae6b38a4448f/.ado/publish.yml#L43

**Comment by NickGerleman** [comment]
The issue is new in 1.49.0 with "Roll-up the changelogs to dependents".

FWIW I'm ecstatic that feature was added in general. The new changelogs were a bit unexpected though.

**Comment by ecraig12345** [comment]
Just noticed we're getting this in Fluent UI React now too, without the bump-deps option... [Example here.](https://github.com/microsoft/fluentui/blob/master/apps/a11y-tests/CHANGELOG.md)

**Comment by dlannoye** [comment]
Fixed by #652
