### ISSUE TITLE
Any chance this package could be ported to a DotNet tool? :)

### ISSUE THREAD

**Issue by NickSevens** [microsoft/beachball#487]
See title :)

This would be an awesome tool to use in our .Net / NuGet projects as well!
Love using it for NPM libraries, but using the same workflow for .net would be super cool :)

**Comment by ecraig12345** [comment]
We have very limited resources to work on beachball right now, so a port to other platforms is extremely unlikely. However since it's MIT-licensed you're welcome to borrow code/ideas to use in a .net tool.
