### ISSUE TITLE
feat: add more user friendly remote resolution for `change/check` command

### ISSUE THREAD

**Issue by Hotell** [microsoft/beachball#490]
Currently if `beachball check` is invoked it will run against `origin` remote by default. 

While this can be changed by explicitly specifying `--branch upstream/master` it would be worth it to add smarter remote resolution that is common to github contribution flow:
- is there a `upstream` remote ?
  - notify user that it's gonna run against `upstream` and explicitly tell him that to change this he needs to use `--branch` flag
- if yes use that by default
- otherwise go with `origin`

**Comment by ecraig12345** [comment]
This is finally done (#34).
