### ISSUE TITLE
Feature: add configuration option to change the name and location of the `change` folder

### ISSUE THREAD

**Issue by JamesBurnside** [microsoft/beachball#500]
Currently the change folder is at `(getWorkspaceRoot(cwd) || gitRoot)/change`.
This is typically `<repo root>/change`

It would be great to have a configuration option to set this, to allow something like:
`<repo root>/common/changeFiles/`

A configuration option could look something like:

Option | Type | Alias | Default | Option Type | Description
-- | -- | -- | -- | -- | --
changeFolder | string |   | change | repo | Folder name including relative path to store the change files

The change likely being to replace `change` here to instead grab/have been passed the configuration option:
https://github.com/microsoft/beachball/blob/7c18046e90a8c1dfb7c28722d0a3812108fc9009/src/paths.ts#L50

**Comment by Azooz2538** [comment]
> يوجد مجلد التغيير حاليًا في `(getWorkspaceRoot(cwd) || gitRoot)/change`. هذا هو عادة`<repo root>/change`
> 
> سيكون من الرائع أن يكون لديك خيار تكوين لتعيين هذا ، للسماح بشيء مثل: `<repo root>/common/changeFiles/`
> 
> يمكن أن يبدو خيار التكوين كما يلي:
> 
> خيار	نوع	الاسم المستعار	تقصير	نوع الخيار	وصف
> تغير مجلد	سلسلة	 	يتغير	الريبو	اسم المجلد بما في ذلك المسار النسبي لتخزين ملفات التغيير
> من المحتمل أن يتم استبدال التغيير `change`هنا بدلاً من الاستيلاء على خيار التكوين / تم تمريره:
> 
> https://github.com/microsoft/beachball/blob/7c18046e90a8c1dfb7c28722d0a3812108fc9009/src/paths.ts#L50

**Comment by MjMoshiri** [comment]
Hi, are these still open I can see that the request is based on a branch that is not merged into the master yet. 
If yes may work on it? if yes again should I add the feature based on the branch mentioned here to the master? 

Thank you in advance 🙏🏻

**Comment by ecraig12345** [comment]
This has been implemented as the `changeDir` option.
