### ISSUE TITLE
Version 2.0.0 missing from CHANGELOG.md

### ISSUE THREAD

**Issue by matthias-ccri** [microsoft/beachball#510]
Notes for version 2.0.0 are missing from CHANGELOG.md, but are present in CHANGELOG.json

- [CHANGELOG.md](https://github.com/microsoft/beachball/blob/79367585d8bc2a33effa4b12705ba063b53d31ee/CHANGELOG.md)
- [CHANGELOG.json](https://github.com/microsoft/beachball/blob/79367585d8bc2a33effa4b12705ba063b53d31ee/CHANGELOG.json#L19-L32)

**Comment by matthias-ccri** [comment]
This probably seems pedantic, I know. But when upgrading from 1.x to 2.x, the main question is what breaking changes were introduced in the 2.0.0 milestone, and people will usually look for a 2.0.0 section in the changelog.

**Comment by ecraig12345** [comment]
That's strange--maybe the bump to 2.0.0 was manual or the publish failed? @kenotron would have a better idea about that, but as a workaround I manually added notes in CHANGELOG.md for that version.
