### ISSUE TITLE
Beachball sometimes ignores description in change file and just prints "Bump xyz to version" to changelog.md

### ISSUE THREAD

**Issue by dcakirkaya** [microsoft/beachball#540]
My change descriptions seem to get ignored by Beachball in the generated changelog files after _some_  beachball publish commands which complete with success. Any insights why this is happening? 

![image](https://user-images.githubusercontent.com/30450946/123361009-2407e180-d523-11eb-8338-e34e8ef540ec.png)
![image](https://user-images.githubusercontent.com/30450946/123361118-56b1da00-d523-11eb-9962-d53c9e5ccea3.png)

using Beachball 2.6.2.

**Comment by dcakirkaya** [comment]
Looks like this is a consistent repro after upgrading to 2.6.2

**Comment by ecraig12345** [comment]
Appears to be fixed by #555 (version 2.6.3)--can you check?

**Comment by dcakirkaya** [comment]
Just verified with 2.10.2 that it's fixed. Thank you !
