### ISSUE TITLE
Adding the option to specify Custom changelog at the package level

### ISSUE THREAD

**Issue by chandpravandan** [microsoft/beachball#550]
Currently the beachball allows to specify a custom schema for the changelog(s) at the repository level. So, we cannot have a custom schema at the package level.

We can have more flexibility in terms of defining a custom schema for the changelog, by allowing developers to specify a custom schema at the package level.

For example -

Currently in the beachball config file we can have -

`changeFilePrompt: { changePrompt: prompt => {} }`

can be like -

`changeFilePrompt: { changePrompt: (prompt, packageName) => { // logic to return the schema based on the packageName }` }

**Comment by chandpravandan** [comment]
I have created a PR for this - https://github.com/microsoft/beachball/pull/545

**Comment by ecraig12345** [comment]
Fixed by #545
