### ISSUE TITLE
Having custom renderer at the package level

### ISSUE THREAD

**Issue by chandpravandan** [microsoft/beachball#551]
Currently the beachball allows to specify a custom renderer for the CHANGELOG.md file at the repository level. So, we cannot have a custom renderer at the package level.

We can have more flexibility in terms of having a custom renderer at the individual package level for the CHANGELOG.md file.

For example -

Currently in the beachball config file we have -

`changelog: { customRenderers: {} }`

which can be like -

`changelog: { packageName1: { customRenderers: {} }, packageName2: { customRenderers: {} } }`

**Comment by chandpravandan** [comment]
I have created a PR for this - https://github.com/microsoft/beachball/pull/544

**Comment by ecraig12345** [comment]
I think this is already possible with the existing implementation. The package name should be accessible via `PackageChangelogRenderInfo.newVersionChangelog.name`, and then you can conditionally modify rendering as needed.
