### ISSUE TITLE
Docs for check command should include tips for GitHub Actions

### ISSUE THREAD

**Issue by jattasNI** [microsoft/beachball#554]
When my repo added the `beachball check` command to a GitHub Action which runs on PRs, it didn't detect changes correctly. The issue turned out to be the same as the one described in #420.

It would have been helpful if the fix from that issue were described in the documentation for the `check` command.

My proposal would be to include something like this in a new GitHub Actions section on the [check](https://microsoft.github.io/beachball/cli/check.html#where-should-check-be-run) docs.
```yml
- uses: actions/checkout@v2
  with: 
    fetch-depth: 0
```

I don't know if that fix is broadly applicable, but it worked in my repo and I see that [Microsoft FAST](https://github.com/microsoft/fast/blob/679b403b190a95cb49c6b74af5c53eb67483ae9e/.github/workflows/ci-daily.yml#L21) uses it too.

**Comment by ecraig12345** [comment]
Thanks, I actually noticed that this was broken in the beachball repo itself too (fixed in #558). 😆

**Comment by kenotron** [comment]
I think in github repos, we should create a beachball github action itself that does this check & release for you ultimately...
