### ISSUE TITLE
Incorrect validation of prerelease change files

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/beachball#564]
For change type `prerelease`, beachball generates a change file like this:
```json
{
  "type": "prerelease",
  "comment": "stuff",
  "packageName": "@fluentui/react-avatar",
  "email": "stuff",
  "dependentChangeType": "patch"
}
```

But then the next time *any command* runs, it validates existing changes and fails with:
`ERROR: there is an invalid dependentChangeType detected @fluentui-react-avatar-b1627c30-8ad9-4845-8b4a-b43f3ae23105.json: "patch" is not a valid dependentChangeType`

**Comment by kenotron** [comment]
This commit broke the validation I think: https://github.com/microsoft/beachball/commit/895323e59aa11cfebf2a6eee0edfaec18f932d51
