### ISSUE TITLE
Multiple change files per package

### ISSUE THREAD

**Issue by matthias-ccri** [microsoft/beachball#572]
When I have a branch with a few changes, e.g. some major, some minor, some none, I can only represent the changes in a single line under a single change type. In this case all the change notes would have to be major because beachball doesn't let me create multiple change files, and a change file only has one bump level (`type`).

Maybe a good solution would be to have the CLI prompt to _add more_ change files for packages that already have them, instead of thinking "since you already have a change file for this package, you don't need another".

**Comment by rdebeasi** [comment]
It's possible to use the beachball CLI to generate an additional change file of a different type: https://github.com/microsoft/beachball/issues/64

That said, this functionality is not super obvious, and I'd love to see a CLI prompt like the one you described.
