### ISSUE TITLE
When publishing from a different branch, do not push to the main remote branch.

### ISSUE THREAD

**Issue by alloy** [microsoft/beachball#607]
I was working on an experimental feature branch and wanted to release some prerelease packages. When I published, beachball pushed all the changes to the remote **main** branch, which was not my intention. Perhaps I overlooked a warning sign, but in general I don't think the default should be this way, but instead push to a remote branch by the same name as the local one.

**Comment by ecraig12345** [comment]
Closing since this is an old issue with no response. If anyone has a similar problem, please open a new issue with full details of the configuration and CLI options you're using.
