### ISSUE TITLE
change and bump look for change files in different directories

### ISSUE THREAD

**Issue by asklar** [microsoft/beachball#616]
project structure:
- root project
  - package (has beachball in project.json dev deps)
  - example

run `beachball change` from the package dir, it creates change file in root under /change
then run `beachball bump`, and it looks for the change file under the package folder, not the root folder

![image](https://user-images.githubusercontent.com/22989529/140449623-882beea2-cb31-48a5-8304-94eddbddcb9d.png)

**Comment by ecraig12345** [comment]
Cleaning up old issues--this should be fixed, or if not, please open a new issue.
