### ISSUE TITLE
Output of check should be customizable

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/beachball#62]
The check command says to run beachball.  I'd like to be able to customize it to say run `yarn checkchange`.

Maybe provide a commandline arg to provide a custom message if `beachball check` fails?  (Or at least the part about how to fix it?)

Also this error message is often going to be the first time people find out about change files. -- maybe we should provide a link to beachball's io page, or a more detailed description of what a change file is, and why its failing their CI?

**Comment by kenotron** [comment]
as you wish! now uses `beachball check --changehint "run yarn change"` to address this!
