### ISSUE TITLE
--prerelease-prefix	doesn't work

### ISSUE THREAD

**Issue by freiksenet** [microsoft/beachball#621]
`beachball publish -t mjs-beta --prerelease-prefix mjs`

```
Validating package version - @graphitation/apollo-mock-client@0.9.0
```

Expected behaviour - have a prefix in version.

**Comment by ecraig12345** [comment]
Probably far too late now, but that isn't the expected behavior. `beachball publish` will only bump versions based on the change files that were previously created; specifying `--prerelease-prefix` with `publish` does nothing.
