### ISSUE TITLE
No changelog command can be found in cli commands

### ISSUE THREAD

**Issue by PorterNan** [microsoft/beachball#634]
According to what is shown in the cli help doc:
![image](https://user-images.githubusercontent.com/11863655/151647231-a46f6273-409a-4777-aad8-44d498ed61cc.png)
There is a changelog command which allows you only generate changelog without bumping the version (So we can do our own version controls), but it is not found in 
https://github.com/microsoft/beachball/blob/master/src/cli.ts

Is it a bug or I just missed something important?

**Comment by ecraig12345** [comment]
That's weird, maybe it was a planned feature that was never added. I'll remove it from the docs for now. (It's a good idea, and someone requested basically this in #650.)
