### ISSUE TITLE
BUG: beachball does not pick up on changes to private dependencies

### ISSUE THREAD

**Issue by bworline** [microsoft/beachball#642]
There are two packages `A` and `B` in the same repo.  `A` is a public package that generates an npm package, `B` is private.  `A` depends on version "*" of `B`.

A change is made to package `B`.  No change file is requested or required because it is private.

BUG: beachball is run but does not detect that `A` is materially different, and so does not bump it.

PROPOSAL: beachball should either blow up or have an option to blow up if it detects private upstream dependencies for a public package.

**Comment by ecraig12345** [comment]
Beachball already errors if a published package has an in-repo private package in its `dependencies`. But if the private package is in `devDependencies`, that's allowed (it's a common scenario for in-repo tooling).

If you're seeing a case where beachball is not erroring on a private package in `dependencies`, a more detailed repro would be needed to debug that.
