### ISSUE TITLE
Beacball publish process failure due to git fail fast

### ISSUE THREAD

**Issue by viditganpi** [microsoft/beachball#714]
The publish step of beachball has a few instances of `gitFailFast` which are not enclosed under any error handling, this leads to failure of the overall process in case `gitFailFast` command fails. 
For example: [Here](https://github.com/microsoft/beachball/blob/a74b1cc94d0f521755dc83a288b79a2a2845bc2a/src/commands/publish.ts#L98) branch deletion sometime results in error, thus failing the overall process. 
This can be handled for error and will fix the overall process.

**Comment by ecraig12345** [comment]
Do you have any idea why the branch deletion is failing for you? It's only a local operation, so it should be very unlikely to fail.

**Comment by viditganpi** [comment]
Not entirely sure, as there is no detailed log but have seen the overall process fail after the step and since there is no error handling for this my best guess is that something fails during deletion.

**Comment by ecraig12345** [comment]
On failure, `gitFailFast` should log `CRITICAL ERROR: running git command` followed by the actual stdout/stderr, so any error should be visible in the logs.
