### ISSUE TITLE
Beachball doesn't suggest previous commit messages when creating a change file

### ISSUE THREAD

**Issue by Bryan-Cee** [microsoft/beachball#784]
When running `beachball change`, the options to `Describe changes (type or choose one)` no longer suggest a list of previouse commits to select from. Example below:

![Screenshot 2022-09-29 at 09 40 50](https://user-images.githubusercontent.com/19145546/192959932-6c0fc256-929a-4330-94fb-c6864945885f.png)

**Comment by ecraig12345** [comment]
This should already be fixed--do you still see it in the latest version?

**Comment by ecraig12345** [comment]
Closing since this should be fixed now. If you're still having a problem, please open a new issue which includes the specific version of beachball you have installed.
