### ISSUE TITLE
ESM support?

### ISSUE THREAD

**Issue by vovsemenv** [microsoft/beachball#789]
reporpduce:

1. add `  "type": "module"` to package.json
1. `npm i -D beachball`
2.  create `beachball.config.js` file
3. `npx beachball check`

```
An error has been detected while running beachball!
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/vladimirsemenov/qameta/allure3/beachball.config.js from /Users/vladimirsemenov/qameta/allure3/node_modules/cosmiconfig/dist/loaders.js not supported.
Instead change the require of beachball.config.js in /Users/vladimirsemenov/qameta/allure3/node_modules/cosmiconfig/dist/loaders.js to a dynamic import() which is available in all CommonJS modules.
```

**Comment by ecraig12345** [comment]
I think you'd need to either change the filename to `beachball.config.cjs`, or change the config file to do `export default { /*contents*/ }` instead of `module.exports = { /*contents*/ }`.

**Comment by vovsemenv** [comment]
Yes, i guess we need to note that in the docs

**Comment by vovsemenv** [comment]
Yes, i guess we need to note that in the docs
