### ISSUE TITLE
[object Object] as commit message option on new branch.

### ISSUE THREAD

**Issue by dake3601** [microsoft/beachball#793]
### Reproduction

- Make a new local branch and switch to it.
- Make a change.
- Run beachball change.
![image](https://user-images.githubusercontent.com/57121448/198745953-602acc95-a80f-48a0-ad68-86f70104a423.png)

### Possible Solution 
- Filter empty messages on promptForChange.ts:
const recentMessageChoices: prompts.Choice[] = recentMessages **.filter(msg => msg !== '')** .map(msg => ({ title: msg }));
- Result:
![image](https://user-images.githubusercontent.com/57121448/198746604-00e46623-aa6b-460d-bf9f-1b5af7f39684.png)

**Comment by dake3601** [comment]
Seems to be happening again on 2.37.0:
![image](https://github.com/microsoft/beachball/assets/57121448/a9337362-8ab9-4024-9c0c-715adac36f02)

**Comment by ecraig12345** [comment]
It looks like I thought I'd fixed this in workspace-tools but didn't actually test the fix--sorry about that! It should be fixed properly in 2.37.1.
