### ISSUE TITLE
Beachball publish  Failure 

### ISSUE THREAD

**Issue by Ravi-kundrapu** [microsoft/beachball#836]
Hey Team, I'm seeing an Issue when I'm running a beachball publish command on my machine

`npx beachball publish --verbose true --yes --new true --push -b master --registry URL --access public`

I only have on JSON file in my change folder `@app-test-7ac89148-e55c-404b-ae62-50835d08c8bd.json`. So I'm assuming it will be bumping only this library without any Issue but I'm running into error's when running the above command. 

```
Validating package version - is-wds@7.0.1
 OK!

Validating package version - @app-notifications@1.1.4
 OK!

Validating package version - @first/box@1.2.1
 OK!

Validating package version - @first/registration@1.2.1
 OK!

Validating package version - @first/mcafee@1.3.1
 OK!

Validating package version - @visa/analytics@2.1.0

ERROR: Attempting to bump to a version that already exists in the registry: @visa/analytics@2.1.0
Validating package version - @visa/XS-fs@1.4.0

ERROR: Attempting to bump to a version that already exists in the registry: @visa/XS-fs@1.4.0
Validating package version - @visa/Se-smbios@1.7.0

ERROR: Attempting to bump to a version that already exists in the registry: @visa/Se-smbios@1.7.0
Validating package version - @visa/K-reg@1.6.0

ERROR: Attempting to bump to a version that already exists in the registry: @visa/K-reg@1.6.0
Validating package version - @visa/Mmi@1.6.0

ERROR: Attempting to bump to a version that already exists in the registry: @visa/Mmi@1.6.0
Validating package version - @visa/c-storage@1.8.0

ERROR: Attempting to bump to a version that already exists in the registry: @visa/c-storage@1.8.0
Something went wrong with publishing! Manually update these package and versions
```

So when run 'GIT STATUS' failing on publish_123456 branch ( temporary branch created by beachball), I see changes in CHANGELOG.json in other libraries as well. 

```
      ' modified:  *********************/app-test/CHANGELOG.json
        modified:   ********************/app-test/CHANGELOG.md
        modified:  *******************/app-test/package.json
        modified:   ******************/first-box/CHANGELOG.json
        modified:   ******************/registration/CHANGELOG.json
        modified:   *****************/first-mcafee/CHANGELOG.json
        modified:   *****************/visa-analytics/CHANGELOG.json
        modified:  ******************/XS-fs/CHANGELOG.json
        modified:  *****************/Se-smbios/CHANGELOG.json
        modified:   ****************/K-reg/CHANGELOG.json
        modified:   *****************/visa-Mmi/CHANGELOG.json
        modified:   *****************/visa-c-storage/CHANGELOG.json' 
```

**Is something  missing here or need to add any of flag for my publish command.  Any suggestions or work around is greatly appreciated**

**Comment by munkherdeneen** [comment]
Could you take a look at this issue please @kenotron, @ecraig12345?

**Comment by ecraig12345** [comment]
Try running `beachball sync --registry <your-registry>` and committing the changes, then retry publishing.

Also, it's best not to post logs which include your private package names, repo structure, or feed URLs in a public GitHub issue, since this can provide potential attackers with clues about your environment. You can change the private stuff to placeholders, like `@my-scope/pkg-1`.

**Comment by Ravi-kundrapu** [comment]
@ecraig12345 We have the same version of library  on the FEED and same version on the GIT package.json file  as well, but still we are getting the above  error. What might be the cause for this ?

  because running beachball sync and committing those changes is not helping these are steps are being followed 

1. Running Publish command  ( we are losing the changelog at this place on a publish_123456 branch) 
2. Running Sync command  ( on the same branch)
3. When we want to run the Publish command we already lost the change log file on first publish run.

**Comment by lancerael** [comment]
I had the same problem for ages and it drove me insane. I fixed this in my monorepo.  I had set an internal dependency to version containing stars ie `"package": "0.*.*"` so Beachball kept trying (and failing) to bump it to the latest version. By setting this to the correct version, it resolved the issue.

**Comment by ecraig12345** [comment]
Closing since this is an old issue and missing details needed to debug.

If this is still a problem, please try to make a simplified GitHub repo which reproduces the problem, and open a new issue.
