### ISSUE TITLE
 bump dependents package versions only when there is relevant change for that Package. 

### ISSUE THREAD

**Issue by Ravi-kundrapu** [microsoft/beachball#908]
Currently we are using beachball in monorepo for publishing, we are ending up publishing all the libraries (115) even only 5 packages have a patch change in them because there is dependency between packages. 

Ideally we would only want to Increment the versions of these 5 packages. We have tried the below options none of them Worked. 

a. Tried setting the` "bumpDeps: False,`" or `"bumpDeps: false,"` in the following file `packages/beachball/src/options/getDefaultOptions.ts`

b. Tried passing --bump-deps=false in the publish command.  

Are there any such known option to get this done ?  If not is there any plan to develop a feature like this going ahead. 

If there is any workaround known to anyone please suggest that would be really helpful.

**Comment by Ravi-kundrapu** [comment]
Could you take a look at this issue please @kenotron, @ecraig12345?

**Comment by ecraig12345** [comment]
You should be able to set this in your beachball config file as `"bumpDeps": false` (modifying beachball code should never be necessary). `--bump-deps=false` on the command line should also work.

If neither of those is working, I'd need to see a repro to figure out what's going on.

**Comment by ecraig12345** [comment]
Thinking about it more, I found an issue where certain boolean command line options weren't being handled properly--so `--no-bump-deps` would have worked, but not `--bump-deps=false`. That will be fixed in the next version 0.36.0. (Setting the option in the config file should work before or after this change.)

**Comment by munkherdeneen** [comment]
> Thinking about it more, I found an issue where certain boolean command line options weren't being handled properly--so `--no-bump-deps` would have worked, but not `--bump-deps=false`. That will be fixed in the next version 2.37.0. (Setting the option in the config file should work before or after this change.)

Hi, @ecraig12345 we have tested all options that "--no-bump-deps", "--bump-deps=false" and "bumpDeps: true" in the config file but none of them worked with the 2.37.0 version.

Did you have a chance to fix the option handling issue in 2.37.0? Thank you.

**Comment by ecraig12345** [comment]
@munkherdeneen I assume you meant `bumpDeps: false` in the config file? Those should be working as far as I know, so I'd need a repro to debug more.

**Comment by munkherdeneen** [comment]
> bumpDeps: true

Yes, I meant bumpDeps: false in the config file and it did not work for me. That would be appreciated @ecraig12345.

**Comment by ecraig12345** [comment]
@munkherdeneen I meant you'd need to provide a repro for me to debug. I can't repro this myself.

**Comment by ecraig12345** [comment]
Closing due to no repro. Please open a new issue with detailed repro steps (or ideally a link to a sample repo that demonstrates the issue) if this is still a problem.
