### ISSUE TITLE
Beachball 2.43.1 ignores prerelease change type, bumped patch on publish

### ISSUE THREAD

**Issue by jonthysell** [microsoft/beachball#964]
The [react-native-windows](https://github.com/microsoft/react-native-windows) mono repo uses beachball and publishes nightly prerelease builds out of main to our canary tag (i.e. with versions `react-native-windows@0.0.0-canary.XYZ`).

Dependabot bumped our beachball from 2.43.0 to 2.43.1, and now beachball has published the very odd `react-native-windows@0.0.1-0`. I see no explanation for this on our end as our change files are still `type: prerelease`, `dependentChangeType: patch`.

Beachball's publish commit (using 2.43.1): https://github.com/microsoft/react-native-windows/commit/0784c77e0b5720026796ad76f4f8c680aa5cf468

Beachball's previous publish commit (using 2.43.0): https://github.com/microsoft/react-native-windows/commit/2731008ee90fe1443d5af4b9ea2975d227787b0d

**Comment by ecraig12345** [comment]
Sorry for the late response--it looks like your beachball version has been updated beyond 2.43.1, so I'm assuming this issue either went away or you found a workaround?
